services:
  jarvis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL_HML}
      - SUPABASE_KEY=${SUPABASE_ANON_KEY_HML}
      - CALLBACK_URL=${CALLBACK_URL:-http://jarvisbot.sytes.net:3001}
    restart: always

networks:
  default:
    name: jarvis_hml_network
